version: 2
jobs:
  build:
    working_directory: ~/Pocket-PiAP-extras-vpn
    docker:
      - image: circleci/buildpack-deps:latest
        environment:
          CI: cicleci
          DEBIAN_FRONTEND: noninteractive
          LANG: en_US.UTF-8
          SHELL: /bin/bash
    steps:
      - run:
          name: "update apt"
          command: |
            sudo apt-get -yq update ; wait ;
      - run:
          name: "upgrade apt"
          command: |
            sudo apt-get -yq dist-upgrade || sudo apt-get -f -y dist-upgrade ; wait ;
      - run:
          name: "install dependencies"
          command: |
            sudo apt-get -y install build-essential make git gnupg2 nginx nginx-full php-fpm php7.0-xsl dnsmasq hostapd python3 python3-pip ; wait ;
      - checkout
      - run:
          shell: /bin/bash
          name: "fetch and pull"
          command: |
            ./.circleci/fetch_and_pull.bash ; wait || true
      - run:
          name: "clean apt"
          command: |
            sudo apt-get autoclean ; wait ;
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean || true
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
      - run:
          shell: /bin/bash
          name: "clean up when done"
          command: |
            make clean
destination: build
 
